stages:
    - dev
    - staging
    - production

deploy_dev:
    stage: dev
    image: kroniak/ssh-client
    script:
        - eval $(ssh-agent -s)
        - ssh-add <(echo "$DEV_SSH_PRIVATE_KEY")
        - mkdir -p ~/.ssh
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        - ssh -t $DEV_SERVER "cd /var/www/backend &&
          git reset --hard &&
          git pull &&
          yarn install &&
          yarn clean &&
          yarn build &&
          yarn db:migrate &&
          pm2 restart processes.json"
    environment:
        name: dev
    variables:
        GIT_STRATEGY: none
    only:
        - dev

deploy_staging:
    stage: staging
    image: kroniak/ssh-client
    script:
        - eval $(ssh-agent -s)
        - ssh-add <(echo "$STG_SSH_PRIVATE_KEY")
        - mkdir -p ~/.ssh
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        - ssh -t $STG_SERVER "cd /var/www/backend &&
          git reset --hard &&
          git pull &&
          yarn install &&
          yarn clean &&
          yarn build &&
          yarn db:migrate &&
          pm2 restart processes.json"
    environment:
        name: staging
    variables:
        GIT_STRATEGY: none
    only:
        - staging

deploy_production:
    stage: production
    image: kroniak/ssh-client
    script:
        - eval $(ssh-agent -s)
        - ssh-add <(echo "$PROD_SSH_PRIVATE_KEY")
        - mkdir -p ~/.ssh
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        - ssh -t $PROD_SERVER "cd /var/www/backend &&
          git reset --hard &&
          git pull &&
          yarn install &&
          yarn clean &&
          yarn build &&
          yarn db:migrate &&
          pm2 restart processes.json"
    environment:
        name: production
    variables:
        GIT_STRATEGY: none
    only:
        - main
